name: qgrid-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - qgrid 
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - seaborn
  - statsmodels
  - biopython
  - regex
  - blast
  - pip:
    - vpnotebook
    - vpython
    - matplotlib_venn
